#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# 画背景域网格
runApplication blockMesh
#提取表面特征线
runApplication surfaceFeatures
#画网格
runParallel snappyHexMesh -overwrite
# 提取液膜表面集合
runApplication topoSet
# 拉伸表面集合形成液膜区域
runApplication extrudeToRegionMesh -overwrite
#保存
paraFoam -touch
paraFoam -touch -region wallFilmRegion

#------------------------------------------------------------------------------
